name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
 
  build-with-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
     
      - name: Build with Gradle
        run: |
                chmod +x gradlew
                ./gradlew build 
                 pwd
   
      - name: Build debug apk
        run: ./gradlew clean assembleDebug

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Example.apk
          asset_content_type: application/zip
   
   
   
   
   
   
                
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test
     

      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
            filename: test.zip     
            exclusions: ' build/distributions/* '  
               
      - name: Create new release
        id: create-new-release
        uses: actions/create-release@latest
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
                run_number
          draft: false
          prerelease: false     

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:  
         upload_url:   ${{ steps.create-new-release.outputs.upload_url }}
         asset_path: ./test.zip
         asset_name: test-v${{ github.run_number }}.zip
         asset_content_type: application/zip



