name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-without-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
               chmod +x gradlew
               ./gradlew build --scan
  build-with-setup-java-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: |
               chmod +x gradlew
               ./gradlew build --scan --no-daemon
  build-with-gradle-build-action-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Run chmod to make gradlew executable
        run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan
  build-with-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: |
               chmod +x gradlew
               ./gradlew build --scan --no-daemon
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test
     

      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
            filename: test.zip     
            exclusions: ' *.cpp / *.c /*.yml  / .git'  
               
      - name: Create new release
        id: create-new-release
        uses: actions/create-release@latest
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
                run_number
          draft: false
          prerelease: false     

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:  
         upload_url:   ${{ steps.create-new-release.outputs.upload_url }}
         asset_path: ./test.zip
         asset_name: test-v${{ github.run_number }}.zip
         asset_content_type: application/zip



