name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
 
  build-with-upload-artifact:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 18.0.2+9
        distribution: 'adopt'

          
    - name: Android JDK install
      run: |
             sudo apt-get install libc6-dev-i386 lib32z1 openjdk-8-jdk
             pwd
             ls -l 
             # cd android_sdk/tools/
             pwd
             cd /usr/local/lib/android/sdk/cmdline-tools/latest/bin/avdmanager
             ls -l
             emulator -list-avds
      
      
  
        
  #  - name: Build with Gradle
  #    run: |
  #              chmod +x gradlew
  #              ./gradlew build
  #              # cd /usr/local/lib/android/sdk/cmdline-tools/latest/bin
               
  #              pwd
  #              ls -l
  #              ./gradlew assembleRelease --no-daemon
  #              java -jar build/libs/gradle-github-actions-example.jar
   
     
     
     
   
   
   
   
   
                
    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
         name: Test report
         path: build/reports/tests/test
     
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
     
     
     
     

    - name: Archive site content
      uses: thedoctor0/zip-release@master
      with:
            filename: test.zip     
            exclusions: ' build/distributions/* '  
               
    - name: Create new release
      id: create-new-release
      uses: actions/create-release@latest
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
                run_number
          draft: false
          prerelease: false     

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:  
         upload_url:   ${{ steps.create-new-release.outputs.upload_url }}
         asset_path: ./test.zip
         asset_name: test-v${{ github.run_number }}.zip
         asset_content_type: application/zip


