name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
 
  build-with-upload-artifact:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 18.0.2+9
        distribution: 'adopt'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build SampleApplication
      run:  |
             chmod +x gradlew
             ./gradlew --no-daemon build
             cd build
             pwd
             ls -l
    
    
    
    
    
    
    
    
    
    
    
    
    
   #   - uses: actions/checkout@v2
       
   #   - name: Android JDK install
   #     run: |
   #          sudo apt-get install libc6-dev-i386 lib32z1 openjdk-8-jdk
   #          pwd
   #          ls -l
      
      
   #   - name: Set up JDK 17
   #     uses: actions/setup-java@v2
   #     with:
   #       java-version: 17
   #       distribution: 'adopt'
   #       cache: gradle
     
     # - name: Install NDK
     #   run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT} 
        
  #  - name: Build with Gradle
  #    run: |
  #              chmod +x gradlew
  #              ./gradlew build
  #              # cd /usr/local/lib/android/sdk/cmdline-tools/latest/bin
               
  #              pwd
  #              ls -l
  #              ./gradlew assembleRelease --no-daemon
  #              java -jar build/libs/gradle-github-actions-example.jar
   
     
     
     
   
   
   
   
   
                
    - name: Archive test report
      uses: actions/upload-artifact@v2
      with:
         name: Test report
         path: build/reports/tests/test
     
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
     
     
     
     

    - name: Archive site content
      uses: thedoctor0/zip-release@master
      with:
            filename: test.zip     
            exclusions: ' build/distributions/* '  
               
    - name: Create new release
      id: create-new-release
      uses: actions/create-release@latest
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
                run_number
          draft: false
          prerelease: false     

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:  
         upload_url:   ${{ steps.create-new-release.outputs.upload_url }}
         asset_path: ./test.zip
         asset_name: test-v${{ github.run_number }}.zip
         asset_content_type: application/zip


